# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test_records.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "test_records.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12test_records.proto\x12\x0ctest_records"L\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t"S\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\r\n\x05stock\x18\x05 \x01(\x05"i\n\x0bRecordUnion\x12&\n\x06person\x18\x01 \x01(\x0b\x32\x14.test_records.PersonH\x00\x12(\n\x07product\x18\x02 \x01(\x0b\x32\x15.test_records.ProductH\x00\x42\x08\n\x06recordb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "test_records_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PERSON"]._serialized_start = 36
    _globals["_PERSON"]._serialized_end = 112
    _globals["_PRODUCT"]._serialized_start = 114
    _globals["_PRODUCT"]._serialized_end = 197
    _globals["_RECORDUNION"]._serialized_start = 199
    _globals["_RECORDUNION"]._serialized_end = 304
# @@protoc_insertion_point(module_scope)
