# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sample.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x06sample\"|\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t\x12\x0c\n\x04tags\x18\x06 \x03(\t\x12 \n\x07\x61\x64\x64ress\x18\x07 \x01(\x0b\x32\x0f.sample.Address\"M\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x13\n\x0bpostal_code\x18\x04 \x01(\t\"[\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\x03\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05total\x18\x04 \x01(\x01\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\"Y\n\x0bRecordUnion\x12 \n\x06person\x18\x01 \x01(\x0b\x32\x0e.sample.PersonH\x00\x12\x1e\n\x05order\x18\x02 \x01(\x0b\x32\r.sample.OrderH\x00\x42\x08\n\x06recordb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON']._serialized_start=24
  _globals['_PERSON']._serialized_end=148
  _globals['_ADDRESS']._serialized_start=150
  _globals['_ADDRESS']._serialized_end=227
  _globals['_ORDER']._serialized_start=229
  _globals['_ORDER']._serialized_end=320
  _globals['_RECORDUNION']._serialized_start=322
  _globals['_RECORDUNION']._serialized_end=411
# @@protoc_insertion_point(module_scope)
